//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L3MSuper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public string Descripcion { get; set; }
        public System.DateTime Fecha_Real { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public int Id_Compra { get; set; }
        public string Proveedor { get; set; }
        public byte[] Foto { get; set; }
        public string Sucursal { get; set; }
    }
}
