//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L3MSuper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajadores
    {
        public int Cedula { get; set; }
        public string Nombre_Completo { get; set; }
        public System.DateTime Fecha_de_Nacimiento { get; set; }
        public System.DateTime Fecha_de_Ingreso { get; set; }
        public string Sucursal { get; set; }
        public int Salario_por_hora { get; set; }
    }
}
