//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L3MSuper.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        public int Cedula { get; set; }
        public int Horas { get; set; }
        public string Sucursal { get; set; }
        public int Semana { get; set; }
        public int Horas_Extra { get; set; }
    
        public virtual Trabajadores Trabajadores { get; set; }
        public virtual Sucursales Sucursales { get; set; }
    }
}
